name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install NPM dependencies
        run: |
          npm install
      - name: Prepare build
        run: |
          npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HEAP_SHOP_9FC28 }}'
          projectId: heap-shop-9fc28
